comics/common/urls.py
from django.conf.urls.defaults import *

from comics.common import views

urlpatterns = patterns('',
    # View top comics
    url(r'^$',
        views.top_latest, name='top-latest'),
    url(r'^\+(?P<days>\d+)/$',
        views.top_show, name='top-last-days'),
    url(r'^(?P<year>\d{4})/$',
        views.top_year, name='top-year'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$',
        views.top_show, name='top-month'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$',
        views.top_show, name='top-date'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/\+(?P<days>\d+)/$',
        views.top_show, name='top-date-days'),

    # View one specific comic
    url(r'^c/$',
        views.comic_list, name='comic-list'),
    url(r'^c/(?P<comic>[0-9a-z-_]+)/$',
        views.comic_latest, name='comic-latest'),
    url(r'^c/(?P<comic>[0-9a-z-_]+)/\+(?P<days>\d+)/$',
        views.comic_show, name='comic-last-days'),
    url(r'^c/(?P<comic>[0-9a-z-_]+)/(?P<year>\d{4})/$',
        views.comic_year, name='comic-year'),
    url(r'^c/(?P<comic>[0-9a-z-_]+)/(?P<year>\d{4})/(?P<month>\d{1,2})/$',
        views.comic_show, name='comic-month'),
    url(r'^c/(?P<comic>[0-9a-z-_]+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$',
        views.comic_show, name='comic-date'),
    url(r'^c/(?P<comic>[0-9a-z-_]+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/\+(?P<days>\d+)/$',
        views.comic_show, name='comic-date-days'),

    # About page
    url(r'^about/$', views.about, name='about'),

    # We do not like robots
    url(r'^robots.txt$', views.robots, name='robots'),
)

comics/common/models.py
import datetime as dt
import time
import os

from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse

from comics.common.managers import ComicManager

class Comic(models.Model):
    LANGUAGES = (
        ('en', 'English'),
        ('no', 'Norwegian'),
    )

    # Required fields
    name = models.CharField(max_length=100,
        help_text='Name of the comic')
    slug = models.SlugField(max_length=100, unique=True,
        verbose_name='Short name',
        help_text='For file paths and URLs')
    language = models.CharField(max_length=2, choices=LANGUAGES,
        help_text='The language of the comic')
    url = models.URLField(verbose_name='URL', blank=True,
        help_text='URL to the official website')

    # Optional fields
    start_date = models.DateField(blank=True, null=True,
        help_text='First published at')
    end_date = models.DateField(blank=True, null=True,
        help_text='Last published at, if comic has been cancelled')
    history_capable_date = models.DateField(blank=True, null=True,
        help_text='Date of oldest release available for crawling')
    history_capable_days = models.PositiveIntegerField(blank=True, null=True,
        help_text='Number of days a release is available for crawling')
    has_reruns = models.BooleanField(default=False,
        help_text='Check to add reruns as new releases')
    schedule = models.CharField(max_length=20, blank=True,
        help_text='On what weekdays the comic is published')
    time_zone = models.IntegerField(blank=True, null=True,
        help_text='In what approximate time zone, in whole hours, '
            + 'relative to UTC, the comic is published')
    rights = models.CharField(max_length=100, blank=True,
        help_text='Author, copyright, and/or licensing information')

    # Automatically populated fields (i.e. for denormalization)
    number_of_sets = models.PositiveIntegerField(default=0,
        help_text='Number of sets the comic is in (automatically updated)')

    objects = ComicManager()

    class Meta:
        db_table = 'comics_comic'
        ordering = ['name']

    def __unicode__(self):
        return u'%s [%s]' % (self.name, self.language)

    def get_absolute_url(self):
        return reverse('comic-latest', kwargs={
            'comic': self.slug,
        })

    def get_feed_url(self):
        return reverse('feeds', kwargs={
            'url': 'c/%s' % self.slug,
        })

    def history_capable(self):
        if self.history_capable_date is not None:
            return self.history_capable_date
        elif self.history_capable_days is not None:
            return (dt.date.today() - dt.timedelta(self.history_capable_days))
        else:
            return dt.date.today()

    def schedule_as_isoweekday(self):
        weekday_mapping = {'Mo': 1, 'Tu': 2, 'We': 3,
            'Th': 4, 'Fr': 5, 'Sa': 6, 'Su': 7}
        iso_schedule = []
        for weekday in self.schedule.split(','):
            iso_schedule.append(weekday_mapping[weekday])
        return iso_schedule

    def datetime_in_time_zone(self):
        if self.time_zone is None:
            return None
        local_time_zone = - time.timezone // 3600
        hour_diff = local_time_zone - self.time_zone
        return dt.datetime.now() - dt.timedelta(hours=hour_diff)


class Release(models.Model):
    # XXX An index ranging over all three fields of this class is CRITICAL for
    # any performance. For PostreSQL use:
    #
    #     CREATE INDEX "comics_release_comic_id_pub_date_strip_id"
    #         ON "comics_release" ("comic_id", "pub_date", "strip_id");

    # Required fields
    comic = models.ForeignKey(Comic)
    pub_date = models.DateField(verbose_name='publication date')
    strip = models.ForeignKey('Strip', related_name='releases')

    class Meta:
        db_table = 'comics_release'
        get_latest_by = 'pub_date'

    def __unicode__(self):
        return u'%s published %s' % (self.comic, self.pub_date)

    def get_absolute_url(self):
        return reverse('comic-date', kwargs={
            'comic': self.comic.slug,
            'year': self.pub_date.year,
            'month': self.pub_date.month,
            'day': self.pub_date.day,
        })


class Strip(models.Model):
    # Required fields
    comic = models.ForeignKey(Comic)
    fetched = models.DateTimeField(auto_now_add=True)
    filename = models.CharField(max_length=100)
    checksum = models.CharField(max_length=64, db_index=True)

    # Optional fields
    title = models.CharField(max_length=100, blank=True)
    text = models.TextField(blank=True)

    class Meta:
        db_table = 'comics_strip'
        get_latest_by = 'pub_date'

    def delete(self, *args, **kwargs):
        super(Strip, self).delete(*args, **kwargs)
        os.remove('%s%s' % (settings.MEDIA_ROOT, self.filename))

    def __unicode__(self):
        return u'%s strip %s' % (self.comic, self.checksum)

    def get_image_url(self):
        return '%s%s' % (settings.COMICS_MEDIA_URL, self.filename)

    def get_first_release(self):
        return self.releases.order_by('pub_date')[0]

comics/common/templates/common/about.html
{% extends "common/base.html" %}


{% block title %}About{% endblock %}


{% block content %}

<h2>About</h2>

<p>Daily Comics is a web based aggregator for web comics. It was originally
developed as a custom web application hosted at
<a href="http://comics.jodal.no/">comics.jodal.no</a>, but the source code has
later been released for others to change and use.</p>

<div class="info floatright">

<h3>
    <img src="{{ MEDIA_URL }}icons/lightbulb.png" alt="" />
    Tips: Keyboard Navigation
</h3>

<p>If you got JavaScript enabled in your browser, you may navigate the comics
using the keyboard. Press the <em>h</em>, <em>j</em>, <em>k</em>, and
<em>l</em> keys to go to the previous page, the comic strip below, the comic
strip above, and the next page, respectively. This feature was contributed by
<a href="http://www.adamcik.no/">Thomas Adamcik</a>.</p>

</div>

<h3>
    <img src="{{ MEDIA_URL }}icons/package.png" alt="" />
    Development
</h3>

<p>Daily Comics is maintained by
<a href="http://www.jodal.no/">Stein Magnus Jodal</a>,
with comments and input from numerous users. The software is freely available
under the GPLv2 license. You can get the source using the version control
system <a href="http://git-scm.com/">git</a> and the command
<code>git clone git://github.com/jodal/comics.git</code>, or you can
<a href="http://github.com/jodal/comics">browse the source</a> online.</p>

<p>Feature requests, bug reports and patches are warmly received, read and
replied to at <a href="mailto:comics@jodal.no">comics@jodal.no</a> or through
the <a href="{% url feedback %}">feedback</a> page.</p>

<h3>
    <img src="{{ MEDIA_URL }}icons/layout.png" alt="" />
    Colophon
</h3>

<p>Daily Comics makes use of
the <a href="http://www.python.org/">Python</a> programming language,
the <a href="http://www.djangoproject.com/">Django</a> web framework,
<a href="http://developer.yahoo.com/yui/">Yahoo! UI Library</a> for style
sheets, and icons from
<a href="http://www.famfamfam.com/lab/icons/silk/">FamFamFam</a>.
<a href="http://www.google.com/analytics/">Google Analytics</a> is used to
gather anonymous information on how the site is used, which is helpful when
trying to improve the site even further.</p>

<p>All output should adhere to the
<a href="http://validator.w3.org/check/referer">XHTML</a>,
<a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a>, and
<a href="http://validator.w3.org/feed/">Atom</a> web standards, and comply with
<a href="http://www.contentquality.com/mynewtester/cynthia.exe?Url1=http://comics.jodal.no/">
Section 508</a>.</p>

{% endblock %}

comics/common/templates/common/comic-list.html
{% extends "common/base.html" %}


{% block title %}List of comics{% endblock %}


{% block content %}

<h2>List of comics</h2>

{% if all_comics %}
<table>
    <tr>
        <th>Comic</th>
        <th>Language</th>
        <th class="alignright">Archive size</th>
        <th class="alignright"># sets</th>
        <th>Website</th>
    </tr>
    {% for comic in all_comics %}
    <tr>
        <td>
            <a href="{{ comic.get_feed_url }}"><img src="{{ MEDIA_URL }}icons/feed.png" width="16" height="16" alt="Comic feed: {{ comic.name }}" title="Comic feed: {{ comic.name }}" /></a>
            <a href="{{ comic.get_absolute_url }}">{{ comic.name }}</a>
        </td>
        <td>{{ comic.get_language_display }}</td>
        {% with comic.strip_set.count as strip_count %}
	<td class="alignright">{{ strip_count }} strip{{ strip_count|pluralize }}</td>
        {% endwith %}
        <td class="alignright">{{ comic.number_of_sets }}
            set{{ comic.number_of_sets|pluralize }}</td>
        <td>{{ comic.url|urlize }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>No comics found.</p>
{% endif %}

{% endblock %}

comics/common/templates/common/release-list.html
{% extends "common/base.html" %}
{% load humanize %}


{% block title %}{{ page.title|safe }}{% endblock %}


{% block extra_head %}
    {{ block.super }}
    {% ifequal page.view_type 'comic' %}
        {% if comics.0.0 %}
            <link rel="alternate" type="application/atom+xml"
                href="{{ comics.0.0.get_feed_url }}"
                title="Comic feed: {{ comics.0.0.name }}" />
        {% endif %}
    {% endifequal %}
    {% ifequal page.view_type 'set' %}
        {% if set %}
            <link rel="alternate" type="application/atom+xml"
                href="{{ set.get_feed_url }}"
                title="Comic set feed: {{ set.name }}" />
        {% endif %}
    {% endifequal %}
    {% if page.first_url %}
        <link rel="start" href="{{ page.first_url }}" />
        <link rel="first" href="{{ page.first_url }}" />
    {% endif %}
    {% if page.prev_url %}
        <link rel="prev" href="{{ page.prev_url }}" />
    {% endif %}
    {% if page.next_url %}
        <link rel="next" href="{{ page.next_url }}" />
    {% endif %}
    {% if page.last_url %}
        <link rel="last" href="{{ page.last_url }}" />
    {% endif %}
{% endblock %}


{% block content %}

{% block comic_top_menu %}
    {% with 1 as top_menu %}
        {% include "common/release-menu.html" %}
    {% endwith %}
{% endblock %}

<h2>{{ page.title|safe }}</h2>


{% ifequal page.view_type 'set' %}
    {% if set %}
    <p class="buttons">
        <a href="{% url set-edit set.name %}">
            <img src="{{ MEDIA_URL }}icons/pencil.png"
                alt="Edit comic set: {{ set.name }}"
                title="Edit comic set: {{ set.name }}" />
            Edit comic set</a>
    </p>
    {% endif %}
{% endifequal %}


<div id="strips">

{% if comics %}
    {% for comic, releases in comics %}
        {% if releases %}
            {% for release in releases %}

<div class="strip">
    <h3 id="strip{{ release.counter }}" class="striptitle">
        <a href="{{ release.get_absolute_url }}">
        {{ release.comic.name }}
        <span class="strippub">published {{ release.pub_date|naturalday }}</span>
        {% if release.strip.title %}&ldquo;{{ release.strip.title|safe }}&rdquo;{% endif %}
        </a>
    </h3>

    {% include "common/release-content.html" %}
</div>

            {% endfor %}
        {% else %}

<div class="strip">
    <h3 class="striptitle">
        <a href="{{ comic.get_absolute_url }}">{{ comic.name }}</a>
    </h3>

    <p>No strip found. See <a href="{% url comic-latest comic.slug %}">the latest strip</a>.</p>
</div>

        {% endif %}
    {% endfor %}
{% else %}
<p>No comics found.
{% if set %}<a href="{% url set-edit set.name %}">Edit set</a> to add comics.{% endif %}</p>
{% endif %}

</div>

{% block comic_bottom_menu %}
    {% with 0 as top_menu %}
        {% include "common/release-menu.html" %}
    {% endwith %}
{% endblock %}

{% endblock %}

comics/common/templates/common/strip-list.html
{% extends "common/base.html" %}
{% load humanize %}


{% block title %}{{ page.title|safe }}{% endblock %}


{% block extra_head %}
    {{ block.super }}
    {% ifequal page.view_type 'comic' %}
        {% if comics.0.0 %}
            <link rel="alternate" type="application/atom+xml"
                href="{{ comics.0.0.get_feed_url }}"
                title="Comic feed: {{ comics.0.0.name }}" />
        {% endif %}
    {% endifequal %}
    {% ifequal page.view_type 'set' %}
        {% if set %}
            <link rel="alternate" type="application/atom+xml"
                href="{{ set.get_feed_url }}"
                title="Comic set feed: {{ set.name }}" />
        {% endif %}
    {% endifequal %}
    {% if page.first_url %}
        <link rel="start" href="{{ page.first_url }}" />
        <link rel="first" href="{{ page.first_url }}" />
    {% endif %}
    {% if page.prev_url %}
        <link rel="prev" href="{{ page.prev_url }}" />
    {% endif %}
    {% if page.next_url %}
        <link rel="next" href="{{ page.next_url }}" />
    {% endif %}
    {% if page.last_url %}
        <link rel="last" href="{{ page.last_url }}" />
    {% endif %}
{% endblock %}


{% block content %}

{% block comic_top_menu %}
    {% with 1 as top_menu %}
        {% include "common/strip-menu.html" %}
    {% endwith %}
{% endblock %}

<h2>{{ page.title|safe }}</h2>


{% ifequal page.view_type 'set' %}
    {% if set %}
    <p class="buttons">
        <a href="{% url set-edit set.name %}">
            <img src="{{ MEDIA_URL }}icons/pencil.png"
                alt="Edit comic set: {{ set.name }}"
                title="Edit comic set: {{ set.name }}" />
            Edit comic set</a>
    </p>
    {% endif %}
{% endifequal %}


<div id="strips">

{% if comics %}
    {% for comic, strips in comics %}
        {% if strips %}
            {% for strip in strips %}

<div class="strip">
    <h3 id="strip{{ strip.counter }}" class="striptitle">
        <a href="{{ strip.get_absolute_url }}">
        {{ strip.comic.name }}
        <span class="strippub">published {{ strip.pub_date|naturalday }}</span>
        {% if strip.title %}&ldquo;{{ strip.title|safe }}&rdquo;{% endif %}</a>
    </h3>

    <p><a href="{{ strip.get_absolute_url }}">
    <img src="{{ strip.get_image_url }}" alt="{{ strip }}"{% if strip.text %} title="{{ strip.text|safe|escape }}"{% endif %} class="stripimg" />
    </a></p>

    {% if strip.text %}
    <p class="striptext">{{ strip.text|safe }}</p>
    {% endif %}

    <p class="stripmeta">
        Credits: {{ strip.comic.rights }}.
        Retrieved at {{ strip.fetched|time }}, {{ strip.fetched|date }}
        from {{ strip.comic.url|urlize }}.
    </p>
</div>

            {% endfor %}
        {% else %}

<div class="strip">
    <h3 class="striptitle">
        <a href="{{ comic.get_absolute_url }}">{{ comic.name }}</a>
    </h3>

    <p>No strip found. See <a href="{% url comic-latest comic.slug %}">the latest strip</a>.</p>
</div>

        {% endif %}
    {% endfor %}
{% else %}
<p>No comics found.
{% if set %}<a href="{% url set-edit set.name %}">Edit set</a> to add comics.{% endif %}</p>
{% endif %}

</div>

{% block comic_bottom_menu %}
    {% with 0 as top_menu %}
        {% include "common/strip-menu.html" %}
    {% endwith %}
{% endblock %}

{% endblock %}

comics/common/templates/common/strip-menu.html
<div class="menu buttons{% if top_menu %} topmenu{% else %} bottommenu{% endif %}">

<div class="navigation">
<ul>
    <li>
{% if page.first_url %}
    <a href="{{ page.first_url }}"{% if top_menu %} id="first"{% endif %}>
{% else %}
    <a class="inactive">
{% endif %}
        <img src="{{ MEDIA_URL }}icons/resultset_first.png" alt="" />
        First</a></li>

    <li>
{% if page.prev_url %}
    <a href="{{ page.prev_url }}"{% if top_menu %} id="prev"{% endif %}>
{% else %}
    <a class="inactive">
{% endif %}
        <img src="{{ MEDIA_URL }}icons/resultset_previous.png" alt="" />
        Previous</a></li>

    <li>
{% if page.next_url %}
    <a href="{{ page.next_url }}"{% if top_menu %} id="next"{% endif %}>
{% else %}
    <a class="inactive">
{% endif %}
        Next
        <img src="{{ MEDIA_URL }}icons/resultset_next.png" alt="" /></a></li>

    <li>
{% if page.last_url %}
    <a href="{{ page.last_url }}"{% if top_menu %} id="last"{% endif %}>
{% else %}
    <a class="inactive">
{% endif %}
        Last
        <img src="{{ MEDIA_URL }}icons/resultset_last.png" alt="" /></a></li>
</ul>
</div>

<div class="timeframe">
<ul>
{% for time_frame in page.time_frames %}
    <li>
    {% if time_frame.url %}
        <a href="{{ time_frame.url }}">
    {% else %}
        <a class="inactive">
    {% endif %}
        <img src="{{ MEDIA_URL }}icons/{{ time_frame.icon }}.png" alt="" />
        {{ time_frame.title }}</a></li>
{% endfor %}
{% ifequal page.view_type 'comic' %}
    {% if comics.0.0 %}
    <li>
        <a href="{{ comics.0.0.get_feed_url }}"
            title="Comic feed: {{ comics.0.0.name }}">
            <img src="{{ MEDIA_URL }}icons/feed.png"
                alt="Comic feed: {{ comics.0.0.name }}" />
            Comic feed</a></li>
    {% endif %}
{% endifequal %}
{% ifequal page.view_type 'set' %}
    {% if set %}
    <li>
        <a href="{{ set.get_feed_url }}"
            title="Comic set feed: {{ set.name }}">
            <img src="{{ MEDIA_URL }}icons/feed.png"
                alt="Comic set feed: {{ set.name }}" />
            Comic set feed</a></li>
    {% endif %}
{% endifequal %}
</ul>
</div>

<hr class="clear" />
</div>